version: "3"
services:
  nodeapp:
    container_name: node
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3306:3306
    
    depends_on:
      - mongodb
    
    networks:
      - node-webapp-network
  
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    networks:
      - node-webapp-network

networks:
  node-webapp-network:
    driver: bridge  
    
  